# Site
repository: BartBurton/bartburton.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Никитин Максим Анатольевич
title: Software Developer
email: bburtonzero@gmail.com
#website: https://github.com/BartBurton

# Dark Mode (true/false/never)
darkmode: never

# Additional icon links
additional_links:
  - title: telegram
    icon: fab fa-telegram
    url: https://t.me/bburtonext

# About Section
about_title: Обо мне
about_profile_image: images/face.jpeg
about_content: |
  

content:
  - title: Образование
    layout: list
    content:
      - layout: left
        title: Московский Политехнический Университет
        caption: 2021 - 2023 (Оконченное)
        sub_title: Бакалавриат "Информационные системы и технологии"
        description: |
          Направление "Программное обеспечения игровой компьютерной индустрии"

      - layout: left
        title: Забайкальский Государственный Университет
        caption: 2018 - 2021 (Неоконченное)
        sub_title: Бакалавриат "Информатика и вычислительная техника"
        description: |
          Направление "Разработка автоматизированных систем"

          В середине третьего курса перевелся в Московский Политех на второй курс.

  - title: Опыт работы
    layout: list
    content:
      - layout: left
        title: Билайн (ВымпелКом-Информационные технологии)
        link: https://moskva.beeline.ru/
        sub_title: Старший Frontend Developer (React, TypeScript)
        caption: Октябрь 2022 — Текущий момент
        description: |
          Разработка и проектирования UI приложений в рамках реализации B2B решений компании:
          - Разработка и проектирование редактора сценариев поведения ботов с искуственным интеллектом.
          - Разработка микрофронтенд приложения умного поиска, основанного на машинном обучении, для упрощения алгоритма завдения внутренних заявок.
      - layout: left
        title: Integro
        link: https://int-group.ru/
        sub_title: Frontend Developer (React, TypeScript)
        caption: Май 2022 — Октябрь 2022
        description: |
          Разработка UI для проектов Департамента строительства города Москвы:
          - Модуль банкинг для интеграции платформы управления строительными проектами с Альфа банком.
          - Микрофронтенд приложение, для построения бизнес процессов в спецификации BPMN.
      - layout: left
        title: Red Wings (ООО "БПО")
        link: https://bpo.travel
        sub_title: Fullstack Developer (.NET/C#, JavaScript)
        caption: Апрель 2021 — Май 2022
        description: |
          Поддержка и реализация продуктов компании, покрывающих различные перечни задач. 
          - В первую очередь сервисы для продажи авиа-билетов B2C и B2B.
          - Реализация и поддержка системы формирования отчетов. Интегрирация системы в сервисы продажи билетов.
          - Обеспечение реализации различных скриптов, утилит и статичных сайтов по требованию компании. В частности, написание скрипты для автоматизации простых, но рутинных задач других сотрудников. Разработка утилит для упрощения выполняемых другими сотрудниками действий. Верстка сайтов для B2C направлений компании.

  - title: Скиллы
    layout: list
    content:
      - layout: left
        title: Gamedev
        description: |
          - Unity, C#, Netcode for GameObjects, URP, AutoLOD,
          C++, SFML, Boost, vcpkg,
          Blender, Mixamo, Piskel, Photoshop, Midjourney, Audacity
      - layout: left
        title: Frontend
        description: |
          - JavaScript, TypeScript, HTML, CSS, React, 
          React Native, VueJS, SCSS, Webpack, Redux, Vuex, 
          Redux Saga, React/Vue Router, React Query, 
          RTK Query, React Hook Form, React Flow, Axios, yup, ESLint, JQuery
      - layout: left
        title: Backend
        description: |
          - .NET/C#, ASP.NET, SQL, MSSQL, EntityFramework, Serilog, 
          AutoMapper, Versioning, ClosedXML, ExcelDataReader, Newtonsoft,
          NodeJS, Koa, PHP, Laravel
      - layout: left
        title: Other
        description: |
          - Git, GitHub, GitLab, Jira, GitHub Projects, Trello, VS Code, Visual Studio, draw.io

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
